### ISSUE TITLE
Termux Support 

### ISSUE THREAD

**Issue by sleeping3119** [ekzhang/sshx#102]
Please make that tool compatible with termux that would be very handy. 
installation:
```
curl -sSf https://sshx.io/get | sed 's|/usr/local/bin|/data/data/com.termux/files/usr/bin|g' | sh
```
Error:  
```
❯ sshx
2024-11-18T22:47:35.651654Z ERROR sshx: transport error

Caused by:
    0: error trying to connect: dns error: failed to lookup address information: Try again
    1: dns error: failed to lookup address information: Try again
    2: failed to lookup address information: Try again

❯ pkg install tsu  #for running with root
❯ sudo sshx
2024-11-18T22:47:35.651654Z ERROR sshx: transport error

Caused by:
    0: error trying to connect: dns error: failed to lookup address information: Try again
    1: dns error: failed to lookup address information: Try again
    2: failed to lookup address information: Try again
```

**Comment by ekzhang** [comment]
Nice! It looks like installation worked, but there's a DNS error from your logs. Any idea where that might be coming from?

**Comment by sleeping3119** [comment]
I don't know, maybe any url is blocked by my dns. Kindly test it on your end.

**Comment by ekzhang** [comment]
I'd need more details -- unfortunately I don't have termux as you can see. Could you try debugging a bit more on your side, with tools like dig, strace or tcptraceroute?

You can use ChatGPT to help with this if you're not familiar with network debugging.

**Comment by sleeping3119** [comment]
i tried you can check logs [here](https://drive.google.com/file/d/1cbe9hmWiKDq4HZB4X9-TXbGCdDvcChYn/view?usp=drivesdk). If there is any specefic command kindly share.

**Comment by sleeping3119** [comment]
```
❯ strace -e trace=network sshx
socketpair(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0, [6, 7]) = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 9
connect(9, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 24) = -1 ENOENT (No such file or directory)
u2024-11-19T01:50:13.337578Z ERROR sshx: transport error

Caused by:
    0: error trying to connect: dns error: failed to lookup address information: Try again
    1: dns error: failed to lookup address information: Try again
    2: failed to lookup address information: Try again
+++ exited with 1 +++
```

**Comment by ekzhang** [comment]
It looks like you have your DNS resolver configured to nscd, and it's not working right now. This is not a bug in sshx and is likely a misconfiguration of DNS on your Termux environment.

These suggestions might help https://chatgpt.com/share/673bff16-7194-800e-9255-6edee8150efc
