### ISSUE TITLE
Access permissions via CLI flags

### ISSUE THREAD

**Issue by Explosion-Scratch** [ekzhang/sshx#17]
Maybe a `sshx --read-only` flag would be nice, so that you can let someone read + scroll on your terminal. Also request to collaborate from the WebUI would be nice. Then this would show a "y/n" style prompt in the terminal where sshx is running.

**Comment by sebadob** [comment]
Maybe an addition to this could be something like a PIN you need to enter when accessing the UI.
The problem is that URLs are not encrypted and anyone sitting in between could just grab it and access the UI.

**Comment by Explosion-Scratch** [comment]
> Maybe an addition to this could be something like a PIN you need to enter when accessing the UI. The problem is that URLs are not encrypted and anyone sitting in between could just grab it and access the UI.

My main problem is that you can't just share a link to let people _view_, this would be so useful for things like YouTube live streams, showing debugging output over zoom, etc, as it would let users scroll back and copy and paste, and you could also safely invite lots of people without worrying about someone running `sudo rm -rf / --no-preserve-root`

**Comment by sebadob** [comment]
> without worrying about someone running `sudo rm -rf / --no-preserve-root`

exactly that :D 

Yes a read-only mode by default with the option to "upgrade" to full access with some key would be very cool.

**Comment by ekzhang** [comment]
While it sounds nice to have, this would add quite a bit of complexity, and I don't think it's so useful to be worth the extra scope for the project right now. If you're doing a live stream, you can just screen-share your terminal. `sshx` is really most interesting for collaborative use cases.

**Comment by casidiablo** [comment]
What a shame... this would have been a nice to have.

Look at it this way: as nerds/hackers our machine is a temple. Opening a sshx session is exciting, but also terrifying as you are explicitly opening a hole in your precious temple.

There's this old project: https://tmate.io/ that does support this feature, by default. It does not have the cooperative nature of sshx, or the "infinite canvas" (unless you count "infinite tmux tabs/panes" as a "canvas"), but it's pretty much equivalent for most use-cases.
