### ISSUE TITLE
Key derivation seems needlessly convoluted

### ISSUE THREAD

**Issue by Shnatsel** [ekzhang/sshx#19]
The way the encryption key is currently derived seems to be:

1.  `rand` gets 128 or more bits entropy from the OS and seeds a `ChaCha` PRNG with that
2. No more than 83 bits of entropy out of it get turned into an alphanumeric string
3. That string is fed to Argon2 to pad it back to 128 bits of length (still 83 bits of entropy)

The straightforward way to derive an encryption key would be just getting 128 bits from the OS entropy source with `getrandom` crate, and that seems superior in every way: it is more secure (128 bits of entropy rather than 83), faster (no intermediate time-consuming cryptography), and results in a smaller download size for both the native binary and web client. When the key needs to be represented in text, it can simply be base64-encoded.

Why is key derivation implemented this way, instead of the seemingly superior straightforward solution?

## References

The key is derived here:

https://github.com/ekzhang/sshx/blob/91c82d46cde4d1ffa0ae34e2a9a49911e2e53baa/crates/sshx/src/controller.rs#L47

where `rand_alphanumeric` uses `rand::ThreadRng` internally:

https://github.com/ekzhang/sshx/blob/91c82d46cde4d1ffa0ae34e2a9a49911e2e53baa/crates/sshx-core/src/lib.rs#L21-L29

The `ThreadRng` is backed by some sort of ChaCha variant, according to `cargo tree`.

After the key is derived it is then fed to Argon2 with a public salt: 

https://github.com/ekzhang/sshx/blob/91c82d46cde4d1ffa0ae34e2a9a49911e2e53baa/crates/sshx/src/encrypt.rs#L7-L10

**Comment by ekzhang** [comment]
The key needs to be short to make the URL shorter. This was a conscious choice, since long URLs are hard to share.

I recognize that rand gets a lot of entropy from the OS, but that's kind of free — it doesn't really make sense for it to request only 83 bits of randomness!

**Comment by Shnatsel** [comment]
Then at the very least you can skip the entirety of `rand` and the `ChaCha` PRNG, and call `getrandom` directly.

**Comment by ekzhang** [comment]
Makes sense! That sounds like a good way to remove a small dependency.

**Comment by Shnatsel** [comment]
I think the main benefit is making the system more cryptographically sound. 

I am convinced that data from `getrandom` still has the same entropy if you run it through `base64` to turn it to ASCII; it is not obvious to me that it still holds when you run it through ChaCha PRNG and then `rand`'s alphanumeric adapter.

**Comment by Shnatsel** [comment]
For comparison, here's a typical encrypted pastebin URL:

https://www.pastevault.com/paste/HqAOOMMTrBgShmIiGZmNXiDT7RA#krik45QzN6gpp14Qni8fhPcviFV3ZuTtO7O33PIOcE3

That's a 256-bit key, to make the encryption quantum-resistant. This should counter the "collect now, decrypt later" programs that three-letter agencies are known to use.

But as long as you don't care about providing confidentiality that's better than the HTTPS outside this encrypted stream, 83 bits of entropy are probably fine.

**Comment by millette** [comment]
Base64 and URLs don't mix that well. That's why there's <https://github.com/magiclen/base64-url>, if that helps here.
