### ISSUE TITLE
Re mprocs TODO

### ISSUE THREAD

**Issue by francislavoie** [ekzhang/sshx#21]
Regarding this line:

https://github.com/ekzhang/sshx/blob/91c82d46cde4d1ffa0ae34e2a9a49911e2e53baa/mprocs.yaml#L15

Pretty sure it's because Node by default doesn't have any SIGTERM handler (`mprocs` defaults to SIGTERM: https://github.com/pvolok/mprocs/blob/c7da714949ca9dff6a83ac020d3b527929d9f979/src/proc/mod.rs#L191), so you need to hook in your own to perform shutdown logic. Setting the stop command to SIGKILL makes it actually stop the process immediately instead of hanging because SIGTERM wasn't handled.

Though you are using `vite dev` and it does have SIGTERM handling https://github.com/vitejs/vite/commit/4338d7d6f32c8e0e67ff58f0cb8c1a9120294756 so :man_shrugging: it should work.

Just wanted to add context in case it's helpful; just came reading this from HN, looks awesome!

**Comment by ekzhang** [comment]
Nice detective work! I had no idea.
