### ISSUE TITLE
Env (or dotfile in HOME) for default server config

### ISSUE THREAD

**Issue by francislavoie** [ekzhang/sshx#22]
Haven't actually played around with this yet, but I was looking at the code (since it's a small codebase): 

https://github.com/ekzhang/sshx/blob/91c82d46cde4d1ffa0ae34e2a9a49911e2e53baa/crates/sshx/src/main.rs#L15-L16

It doesn't seem like there's a way to set a different default for `--server`.

In cases where the server is self-hosted, I envision it would be preferred to have this set in env (in my `.bashrc`, e.g. `SSHX_SERVER=https://sshx.internal-domain.com`) or via a dotfile of somekind.

This would avoid the "risk" of accidentally using `sshx.io` when data trust is important (corporate network etc), and making it easier to use by default.

Alternative is to make a bash alias with `--server` always set, I guess, but that kinda feels worse than proper config.

**Comment by ekzhang** [comment]
Thank you for sharing your use case and the suggestion! I added support for it as an environment variable.
