### ISSUE TITLE
Binary handling on MacOS/Ventura

### ISSUE THREAD

**Issue by brendan-stephens** [ekzhang/sshx#28]
There's no `/usr/local/bin` path, by default, on Ventrua.
And no handling if the path doesn't exist:
```
printf "\n${ansi_reset}${ansi_info}↯ Adding sshx binary to ${ansi_underline}%s${ansi_reset}\n" "/usr/local/bin"
if [ "$(id -u)" -ne 0 ]; then
  sudo tar xf "$temp" -C /usr/local/bin
else
  tar xf "$temp" -C /usr/local/bin
fi
```

```
↯ Adding sshx binary to /usr/local/bin
tar: could not chdir to '/usr/local/bin'


↯ Done! You can now run sshx.
```

The target can be added (including `PATH`).
Optionally, a brew (or other) package may be helpful here for Mac installs.

**Comment by superlopuh** [comment]
Brew would be great, it feels safer to install things with brew than by piping to shell with sudo

**Comment by superlopuh** [comment]
Brew now installs binaries to `/opt/homebrew/` on my machine FWIW

**Comment by ekzhang** [comment]
Fair enough! I previously wrote another CLI tool that was [packaged on Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/b/bore-cli.rb), I think we'll probably just wait a while and see if there's enough interest.

**Comment by davinkevin** [comment]
Interest in brew package for me too!
