### ISSUE TITLE
How to self host sshx server

### ISSUE THREAD

**Issue by lidh15** [ekzhang/sshx#30]
in my case, https://sshx.io is not accessible. how do I define a sshx server for myself?

**Comment by ekzhang** [comment]
I hope to offer self-hosting support in the future, but it's kind of time-consuming already to create sshx myself, so it's not officially supported at the moment. If you're a business who is reading this and would like to self-host sshx, let me know, I'm thinking I would charge a small fee per server for an enterprise version with self-hosting support.

**Comment by ariary** [comment]
I'm not sure it's answering your question but you can self host sshx server cf [developement](https://github.com/ekzhang/sshx#development)

```bash
docker compose up
# clone the repo
npm install
npm run dev
#in another window
cargo run --bin sshx-server --  --override-origin http://localhost:5173  --secret dev-secret  --redis-url redis://localhost:12601
```

And to use the client `sshx  --server http://127.1:8051`

It is up to you to handle how your expose the npm and sshx server then

**Comment by ekzhang** [comment]
Re: Above please do not do this! This is extremely insecure. Do not expose the Vite development server to the world.
