### ISSUE TITLE
github actions how to stop

### ISSUE THREAD

**Issue by rjrobben** [ekzhang/sshx#33]
For github action usage:

After opening a terminal with 
`run: curl -sSf https://sshx.io/get | sh && sshx`

Is it possible to gracefully shut it down and let the action proceed?

The container can be shut down with e.g. linux shutdown command, but then the workflow is not passed.

Great project, thanks a lot!

**Comment by ekzhang** [comment]
Of course! Hmm, you could run `killall sshx` — that should send SIGTERM to the process and gracefully exit.
