### ISSUE TITLE
How about supporting trzsz ( trz / tsz ) ? Which similar to lrzsz ( rz / sz ).

### ISSUE THREAD

**Issue by lonnywong** [ekzhang/sshx#34]
GitHub: https://github.com/trzsz/trzsz.js

![browser example](https://trzsz.github.io/images/browser.gif)

**Comment by ekzhang** [comment]
Wow that's neat! How does `trz` work, and is there a popular standard for this? Do other terminals support it?

**Comment by lonnywong** [comment]
`trz` read content from stdin, and save it to a file.

It's custom protocol, works like lrzsz ( rz / sz), and compatible with `tmux`, better than rz / sz.

There  are some terminals support trzsz:
- https://github.com/tsl0922/ttyd
- https://github.com/electerm/electerm
- https://github.com/Eugeny/tabby （by a plugin ）
- https://github.com/gnachman/iTerm2  (by a trigger )

On other terminals, we can use  https://github.com/trzsz/trzsz-ssh or https://github.com/trzsz/trzsz-go to support trzsz.
