### ISSUE TITLE
run sshx in the background

### ISSUE THREAD

**Issue by Milo123459** [ekzhang/sshx#37]
perhaps `sshx -b` would allow you to run a sshx session without blocking the current shell and instead running it in a background thread.

**Comment by ekzhang** [comment]
I might be misunderstanding — is it sufficient to just run `sshx &` to have it in the background for your use case?

I'm a bit hesitant about daemonizing processes; it takes a lot of care to do correctly in a way that doesn't accidentally leave processes hanging around as children of PID 1, especially for something as sensitive as sharing your terminal.

**Comment by Milo123459** [comment]
what if you want to get logs from the `sshx` client, along with what if i want to kill the process?

**Comment by stevenhao** [comment]
i see this as closed, here's a workaround:

```
[Unit]
Description=sshx daemon service
After=network.target

[Service]
ExecStart=/usr/local/bin/sshx
User=ubuntu
Restart=always

[Install]
WantedBy=multi-user.target
```

on linux:
```
sudo cp sshx.service /etc/systemd/system/ && sudo systemctl daemon-reload
sudo systemctl enable sshx.service
```
