### ISSUE TITLE
Feature request | Copy/Paste support on web terminal(such as sshx.io)

### ISSUE THREAD

**Issue by likev** [ekzhang/sshx#41]
There is a long history of xterm.js not work well with Copy/Paste keyboard shortcuts or mouse https://github.com/xtermjs/xterm.js/issues/2478 ,some keyboard shortcuts may work on certain browser but not for all browser

 * Copy: `Ctrl+Insert` `Ctrl+Shift+C` `mouse+select+copy`
 * Paste: `Shift+Insert` `Ctrl+Shift+V`

Can we fix this?

**Comment by ekzhang** [comment]
Not enough details

**Comment by edizeqiri** [comment]
I think he is referring to the fact that copy/paste does not fully work. You can paste with `Ctrl+Shift+V` but not copy with `Ctrl+Shift+C `.

This would be a nice feature to add.

**Comment by pinpox** [comment]
@ekzhang please reopen, still relevant. Copying with ctrl+shift+c opens the dev tools instead of copying.
