### ISSUE TITLE
Server refusing connection

### ISSUE THREAD

**Issue by lysol33** [ekzhang/sshx#43]
I'm encountering issues while running the development environment with 'mprocs.' The 'sshx' client app is throwing the following error:

`ERROR sshx: transport error

Caused by:
    0: error trying to connect: tcp connect error: Connection refused (os error 111)
    1: tcp connect error: Connection refused (os error 111)
    2: Connection refused (os error 111)`

Node version: 18.16.0
NPM version: 9.5.1
Rust version: 1.71.1

The server and web components are running without any problems. Any ideas on how to debug this?

**Comment by ekzhang** [comment]
You need to press "r" to restart the client in development if it starts before the server.

**Comment by lysol33** [comment]
I've tried that already. No help, still crashing

**Comment by ekzhang** [comment]
What operating system are you on? Can you check if `sshx-server` is listening on port 8051?

**Comment by lysol33** [comment]
Ubuntu 22.04
It does listen
`sshx-serv  TCP ip6-localhost:8051 (LISTEN)`

**Comment by ekzhang** [comment]
Hmm, it might be an issue with IPv6 versus IPv4 configuration on your local machine. Try it with --server http://[::1]:8051 instead, as well as http://127.0.0.1:8051

**Comment by lysol33** [comment]
Nice! Appears that was the issue. '--server http://[::1]:8051' did the trick. Thanks!
