### ISSUE TITLE
Connecting

### ISSUE THREAD

**Issue by bcdlbgm** [ekzhang/sshx#44]
When I set up sshx myself and run mproc, the top left corner always displays "Connecting".

**Comment by natarajan0007** [comment]
could you share the log? i was able to make it working without any issue.

**Comment by bcdlbgm** [comment]
start.yaml
 # prettier-ignore
   2   │ procs:
   3   │   server:
   4   │     shell: >-
   5   │       cargo run --bin sshx-server --
   6   │       --listen 0.0.0.0
   7   │       --override-origin http://0.0.0.0:5173
   8   │       --secret dev-secret
   9   │       --redis-url redis://127.0.0.1:6379
  10   │   client:
  11   │     shell: >-
  12   │       cargo run --bin sshx --
  13   │       --server http://0.0.0.0:8051
  14   │   web:
  15   │     shell: npm run dev -- --host 0.0.0.0
  16   │     stop: SIGKILL  # TODO: Why is this necessary?

mprocs -c start.yaml

./sshx --server http://x.x.x.x:8051

and
<img width="1443" alt="image" src="https://github.com/ekzhang/sshx/assets/45490024/ca2245be-e664-4504-a1c3-52c78f35f143">
always displays "Connecting"

**Comment by natarajan0007** [comment]
are you running the redis ?

**Comment by bcdlbgm** [comment]
<img width="331" alt="image" src="https://github.com/ekzhang/sshx/assets/45490024/36eac55d-58a6-413c-a1a3-12878a86a1e7">
yes i'm running redis

**Comment by natarajan0007** [comment]
Looks good to me do you see any error message on browser console or network section.?

**Comment by bcdlbgm** [comment]
<img width="1260" alt="image" src="https://github.com/ekzhang/sshx/assets/45490024/fca0c387-22af-4ec6-aaed-db8060b13b49">

![image](https://github.com/ekzhang/sshx/assets/45490024/2296dda8-a7af-4f6d-a004-5e30594605a1)

I don't see any errors on sshx。

**Comment by natarajan0007** [comment]
Why do you need to run sshx-server to run on 0.0.0.0 rather than local host? . the only thing i exposed is front end over 0.0.0.0 and rest are running on local host?. I

**Comment by natarajan0007** [comment]
`./sshx-server --override-origin http://localhost:5173 --secret dev-secret --redis-url redis://localhost:6379 `
 just use like this

**Comment by ekzhang** [comment]
Thanks @natarajan0007 -- for security reasons, I can't recommend you run anything bound to the unspecified IP address (0.0.0.0 or ::) in development.

And in your case, attempting to connect to 0.0.0.0 as a destination IP address is invalid

**Comment by bcdlbgm** [comment]
I restarted and followed the command you said, but still “Connectinging”

**Comment by natarajan0007** [comment]
could you share the log again?

**Comment by bcdlbgm** [comment]
![image](https://github.com/ekzhang/sshx/assets/45490024/7f343514-d44b-4e90-8a78-588556cd5710)
![image](https://github.com/ekzhang/sshx/assets/45490024/4000f4a0-6230-4e6a-ada6-6c9c87694193)

**Comment by natarajan0007** [comment]
can you share the frontend log also?

**Comment by bcdlbgm** [comment]
i no`t see frontend log

**Comment by natarajan0007** [comment]
when you execute mprocs you will get the three status. I am running it in dev mode 
![image](https://github.com/ekzhang/sshx/assets/17359328/f68823fc-a026-4199-9ecd-fa0b71808b05)

**Comment by bcdlbgm** [comment]
The two screenshots I posted are the ones here with debug enabled.
<img width="715" alt="image" src="https://github.com/ekzhang/sshx/assets/45490024/12829155-5502-4502-8ae4-ab4507410bc4">

**Comment by bcdlbgm** [comment]
The problem is solved. Some front-end APIs need to be used in a security context. You can use sshx normally by turning on https.

**Comment by 0xorOne** [comment]
Please tell me how to deploy the sshx server, Thank you.
