### ISSUE TITLE
feature request: expose ssh server

### ISSUE THREAD

**Issue by uxtstr23** [ekzhang/sshx#46]
[tmate](https://tmate.io/) exposes an ssh server, i.e: `ssh PMhmes4XeKQyBR2JtvnQt6BJw@nyc1.tmate.io`

web-based is a nice idea, but it's not as fast and bandwidth-saving as connecting via an ssh client

i believe supporting SSH server exposion will make sshx much better than tmate

**Comment by natarajan0007** [comment]
@uxtstr23  what do you mean by expose an ssh server? you can still do with do with sshx.

**Comment by uxtstr23** [comment]
@natarajan0007 how? i found no such feature in the help.

**Comment by ekzhang** [comment]
Cool idea! I think this is unlikely to be possible without significant internal changes though given the architecture of sshx — which operates entirely over Layer 7 load balancing.

Also, I can't detect people's cursors, move terminals around on the canvas, and share changes over a terminal-based client, so the experience would not be as good.

**Comment by uxtstr23** [comment]
@ekzhang

> Cool idea! I think this is unlikely to be possible without significant internal changes though given the architecture of sshx

i totally agree with you


> I can't detect people's cursors, move terminals around on the canvas, and share changes over a terminal-based client

that's the "acceptable" limit of terminal-based client

i think `sshx` should have different 2 use-cases:
1. web ui is really awesome for someone who want full-featured (and must have fast enough internet connection) that you've made very well
2. terminal-based client is extremely useful for people who want a ssh server only
