### ISSUE TITLE
[bug] Zombie Process and Memory Leak on Termination

### ISSUE THREAD

**Issue by jerryokk** [ekzhang/sshx#49]
I have identified a critical issue on my embedded device (aarch64 architecture). Upon running a specific process in the terminal, I observed that when I close the terminal, it leaves behind a zombie process, and the associated memory is not reclaimed, causing continuous memory growth. This is impacting system performance and may have adverse effects on other processes and device functionalities.

Device Information:
* Architecture: aarch64
* Operating System: linux
* Relevant Process: adbd --> bash --> sshx --> bash

![image](https://github.com/ekzhang/sshx/assets/126859008/fde84a68-d2f8-49a8-a810-1c4540f6ba6a)

**Comment by ekzhang** [comment]
Shouldn't the init process reap zombies? Is this embedded system set up with an init process?

We can call waitpid() if you want but I wouldn't call it a "critical issue" — this seems like a idiosyncrasy of your system

**Comment by jerryokk** [comment]
> Shouldn't the init process reap zombies? Is this embedded system set up with an init process?
> 
> We can call waitpid() if you want but I wouldn't call it a "critical issue" — this seems like a idiosyncrasy of your system

The same thing happens when I use wsl, which will generate zombie processes.

![image](https://github.com/ekzhang/sshx/assets/126859008/5c80dafe-3e97-4a9b-bd9d-59ab7e1b566d)

I think `waitpid()` is necessary.

**Comment by ekzhang** [comment]
Ah, you're speaking of the process taking up a slot in the pid table while sshx is still running. Yes, that's fair, it does not create any OS scheduler overhead and will be cleaned up when sshx terminates though.

Once again, this is not a critical issue. I'll see what I can do though!
