### ISSUE TITLE
Version number in download file

### ISSUE THREAD

**Issue by sebdanielsson** [ekzhang/sshx#50]
Hi! Cool utility! I wanna put this in the Homebrew repo but first it would be nice if you could put the version number in the download file. Also, using Github tags and releases would be great. You can upload the release files for each release for free with Github Actions.

**Comment by alerque** [comment]
Agree. Working on packaging this for Arch Linux but we really need a tagged releases. I'll probably reverse-engineer from the crates.io release for 0.2.0, but please do add Git tags for all release points.

**Comment by ekzhang** [comment]
Fantastic! I don't have this set up yet but will do soon.

**Comment by alerque** [comment]
```console
$ git tag v0.1.0 6f6284b
$ git tag v0.2.0 bd81c86
$ git push --tags
```

**Comment by ekzhang** [comment]
Please, have patience, we will do it soon. I have set up automated release processes in the past but it takes time to set up correctly. And `v0.1.0` is not an official release.
