### ISSUE TITLE
Creating a terminal in Alpine Linux exits immediately

### ISSUE THREAD

**Issue by gmile** [ekzhang/sshx#56]
I'm getting an UNSUPPORTED_OS, like on the screenshot:

<img width="1151" alt="image" src="https://github.com/ekzhang/sshx/assets/207112/3fc95396-5392-403e-93ee-df7d52b309e5">

I'm not sure where this error is coming from, and how to fix it. Happy to provide more details, but not sure what those would be at point 🤔 

I'm trying to connect to an Alpine-based container, running in GitHub Actions.

**Comment by ekzhang** [comment]
Weird, I haven't seen that one before. Thanks for the report. Do you have a reproduction that I could take a look at?

**Comment by ekzhang** [comment]
I have a reproduction — I just tried in an alpine container, and the terminals immediately close as soon as they're created. Interesting! Maybe it's a quirk of busybox.

<img width="540" alt="image" src="https://github.com/ekzhang/sshx/assets/7550632/ccce1f11-1518-4b20-8696-26f543793346">

```bash
docker run -it --rm alpine:latest
apk add curl
curl https://sshx.io/get | sh
sshx
```

The "subsystem status" error you're seeing is coming from a content script, so it probably doesn't have anything to do with sshx. I can't reproduce that part.

**Comment by ekzhang** [comment]
Found the issue, it's because my default shell auto-detection isn't a particularly advanced heuristic. On most shells `$SHELL` is set, but otherwise I default to `/bin/bash`. I guess we could first check to see if `/bin/bash` is present and use `/bin/sh` otherwise.
