### ISSUE TITLE
How to self host the sshx server?

### ISSUE THREAD

**Issue by edizeqiri** [ekzhang/sshx#57]
Hi, I am currently trying to run the server locally.

## What I did

```bash
docker build -t sshx .
docker run -p 8051:8051 sshx:latest
```

![image](https://github.com/ekzhang/sshx/assets/89740646/3bab922e-b444-4032-91c9-6829503876c9)

![image](https://github.com/ekzhang/sshx/assets/89740646/3181d3b2-4b3f-4e80-b8b8-51e411bff9d6)

Issue is not only for WSL.
Am I missing a step?

**Comment by edizeqiri** [comment]
I found it out.

if using nginx then or nginx proxy manager add this:

`
location /sshx.SshxService/Channel {
   grpc_pass      grpc://192.168.1.132:8051;
}

Btw @ekzhang, can I make a pull request and add the documentation for selfhosting this with docker and nginx? I think this would safe a lot headache for someone else trying to selfhost it.
`

**Comment by ekzhang** [comment]
192.168.0.0/16 is a local IP range

You're welcome to make PRs for the guide but I won't accept them unless the documentation is correct, safe, well-written, and considers all cases.

If you're not an expert on Nginx configuration and understand why grpc_pass is necessary I wouldn't recommend it.

**Comment by thyseus** [comment]
@ekzhang sorry for digging out this old topic but self-hosting seems to be a demanded feature.

if i get it right, self-hosting is *possible* but there is not yet an official document that describes, how. 

Is that correct ?

Thanks a lot for your great Software !
