### ISSUE TITLE
selft hosted - nixOS 

### ISSUE THREAD

**Issue by realsnick** [ekzhang/sshx#75]
Hi, beautiful solution! thank you for contributing this to open source! 

This can be a great solution for our open source [Sky360 ](https://sky360.org) in order to help with remote support. 

I can help with contributing how to self-host it on nixOS

[ ] HTTP/TCP reverse proxies
[ ] gRPC forwarding
[ ] TLS termination
[ ] private mesh networking
[ ] graceful shutdown

I believe most can be done via a configuration of nginx, please correct me if i'm wrong.

**Comment by ekzhang** [comment]
Self-hosting is not supported at the moment, and I don't really want to review and maintain a guide written by a non-expert, which will likely be a lot of work for me.

**Comment by realsnick** [comment]
guess you don't want a contribution for self-hosting...too bad, not sure we can move forward with your solution due to security risks... let me know if you change your mind

**Comment by realsnick** [comment]
#76
