### ISSUE TITLE
[Feature request] Support for armv6l, armv7l 

### ISSUE THREAD

**Issue by danieltroger** [ekzhang/sshx#78]
Hi, would much appreciate if you could add support for the original raspberry pi zero w, getting

> Unsupported arch armv6l

on it right now.

Also on my Odroid XU4:

> Unsupported arch armv7l

**Comment by ekzhang** [comment]
I'll try! Seems like the right targets would be `arm-unknown-linux-musleabihf` for your raspberry pi zero w, and `armv7-unknown-linux-musleabihf` for your Oxdroid XU4. Both have hard-float support.

**Comment by ekzhang** [comment]
I don't have an armv6 / armv7 device to try this out on, but let me know if it works.

**Comment by danieltroger** [comment]
Wow, that was quick, thanks a lot @ekzhang!

Getting this on my raspberry pi zero w:

```
pi@energy:~ $ curl -sSf https://sshx.io/get | sh
sh: 23: suffix+=eabihf: not found
↯ Downloading sshx from https://s3.amazonaws.com/sshx/sshx-arm-unknown-linux-musl.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   305    0   305    0     0    259      0 --:--:--  0:00:01 --:--:--   259
Error: Request had status code 404.
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>sshx-arm-unknown-linux-musl.tar.gz</Key><RequestId>EH8C35QMS66TBAB1</RequestId><HostId>z2UM6fBK0dPf3nqpld6/y5sqSeWbXIKeDdQPJM9WMSKafdTnzJJTgKAoq568tUSjmtA0v4nJ224=</HostId></Error>
```

And this on the odroid XU4:

```
odroid@odroid:~$ curl -sSf https://sshx.io/get | sh
sh: 24: suffix+=eabihf: not found
↯ Downloading sshx from https://s3.amazonaws.com/sshx/sshx-armv7-unknown-linux-musl.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   307    0   307    0     0    551      0 --:--:-- --:--:-- --:--:--   557
Error: Request had status code 404.
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>sshx-armv7-unknown-linux-musl.tar.gz</Key><RequestId>ZS794CYYSQYCWSVV</RequestId><HostId>SN6o1SgW9Kr7SrmMrvBDuahL22vcmSfBHHXJC9pJm3WjwmZdYKNRg2LkL0pu3SJeNmJoBWk7e8o=</HostId></Error>
odroid@odroid:~$ 
```


Let me know if you want me to run any commands to send you some info!
```

**Comment by ekzhang** [comment]
Oops, looks like `+=` doesn't work on your `sh`.

**Comment by ekzhang** [comment]
I made this change, try again in 30 minutes? https://github.com/ekzhang/sshx/commit/fc404222f41b80eec477245d365df48950084038

**Comment by danieltroger** [comment]
I tried downloading it manually (odroid xu4: https://s3.amazonaws.com/sshx/sshx-armv7-unknown-linux-musleabihf.tar.gz, raspberrypi: https://s3.amazonaws.com/sshx/sshx-arm-unknown-linux-musleabihf.tar.gz)

And it works flawelessly! So it's just the install script that didn't work.

Super nice tool, thanks a lot for making it and adding more arch support.

**Comment by ekzhang** [comment]
Awesome thanks so much for verifying! Glad it just works on your odroid :D

**Comment by danieltroger** [comment]
Sorry for the confusion, I wrote my last comment without seeing your reply that you updated the install script because I didn't reload the page before writing it.

But I tested the install script now and it works!

On the pi:

```
↯ Downloading sshx from https://s3.amazonaws.com/sshx/sshx-arm-unknown-linux-musleabihf.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2518k  100 2518k    0     0  1202k      0  0:00:02  0:00:02 --:--:-- 1202k

↯ Adding sshx binary to /usr/local/bin

↯ Done! You can now run sshx.
```

And on the odroid:

```
odroid@odroid:~$ curl -sSf https://sshx.io/get | sh
↯ Downloading sshx from https://s3.amazonaws.com/sshx/sshx-armv7-unknown-linux-musleabihf.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2475k  100 2475k    0     0  1758k      0  0:00:01  0:00:01 --:--:-- 1764k

↯ Adding sshx binary to /usr/local/bin

↯ Done! You can now run sshx.
```

So now everything fully works on both :) Thansk again!
