### ISSUE TITLE
transport error

### ISSUE THREAD

**Issue by UyCode** [ekzhang/sshx#83]
![image](https://github.com/ekzhang/sshx/assets/24651136/4cea486c-8998-4f62-b57d-0d0484d3a121)

**Comment by Earthones** [comment]
I meet this problem also, I look up but no any resolution, who can help me, thank you! 
> ./sshx
2025-01-17T09:08:42.953892Z ERROR sshx: transport error
Caused by:
    0: error trying to connect: received fatal alert: NoApplicationProtocol
    1: received fatal alert: NoApplicationProtocol
