### ISSUE TITLE
Windows client support

### ISSUE THREAD

**Issue by ekzhang** [ekzhang/sshx#87]
(It looks like due to a bug or some other issue on GitHub, the previous issue for Windows support is not showing up, so I'm going to make a new one.)

The sshx client is mostly cross-platform, except one file [`terminal.rs`](https://github.com/ekzhang/sshx/blob/main/crates/sshx/src/terminal.rs). To add Windows support, we would need to port terminal.rs to Windows using the [ConPTY API](https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/).

**Comment by thewh1teagle** [comment]
Hey!
What's the status of this feature?

**Comment by ekzhang** [comment]
You're welcome to help implement it! It's the same as before.

**Comment by wll8** [comment]
Super looking forward to implementing it on Windows

**Comment by ekzhang** [comment]
Me too! Please give me a holler if you'd like to work on it

**Comment by ekzhang** [comment]
I had some time today and am mostly caught up on emails, so I went ahead and spun up a Windows VM on AWS and made a dev environment. Such a pain to even set up SSH compared to Linux! But that's what it is, remote desktop protocol and so on.

There is a PR #99 that adds Windows support to sshx. Please test and let me know if it works for you. You can build within the branch with `cargo run -p sshx`. Thanks!

I'm especially interested in hearing if the shell detection is working right. Powershell doesn't seem to be launching, besides that I'm just auto-detecting for git bash and cmd right now. Anything else people use commonly / stats about this? Cygwin?
