### ISSUE TITLE
ability to zoom out, so one can find the right window (enhancement request) 

### ISSUE THREAD

**Issue by nslieske** [ekzhang/sshx#88]
Awesome app, thank you for all the hard work to put it together. If I can help to implement, please let me know how best to do that. 

Practically speaking, it's very tough to find shells in the infinite landscape:

![image](https://github.com/ekzhang/sshx/assets/83024770/c1da849e-586c-4339-9189-7092208b222d)

How could we make it easy to zoom in & out to find windows?  Apologies if I missed this function.  Here's an example with google chrome zoom out feature, which is less than ideal:

![image](https://github.com/ekzhang/sshx/assets/83024770/621c8d19-0755-462c-8814-c5d8051bea42)

**Comment by ekzhang** [comment]
On a laptop trackpad or mobile touchscreen, you can simply drag your fingers in and out. On other computers, you can hold the Ctrl key and scroll up and down while not focused on a terminal.

**Comment by nslieske** [comment]
I just found that.. thanks again

**Comment by ekzhang** [comment]
You're welcome! Getting this question makes me happy that sshx has implemented this feature :)
